runtime: php
env: flex
 
runtime_config:
  document_root: public
 
# Ensure we skip ".env", which is only for local development
skip_files:
  - .env
 
env_variables:
  # Put production environment variables here.
  GCS_ACCESS_KEY_ID: 105046148990098211937
  # GOOGLE_APPLICATION_CREDENTIALS: /public/Eklesia-e155e26b068d.json
  GCS_SECRET_ACCESS_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvlYIwa01UMRud\n2cPa28xQTLI+t2AD+BqJOpH6K/PTxVqhThgZpkWaoYnA/XJGEThXK6f9JR4hnX4Y\nJrTNcTdu6dTGag+rl4k1TojP+n3A86ruZnhWz8PdUmTcD5C7zjcLvk8lXJ0mps6c\na5+UACysWjEOvT5L6d5xzWhd3yrdHIOCBk1wiXSfrInH/rXdXxrZ02/F3Ly+AcoW\na8iUXDhhjb86Q/Tx3v8NuuGVwDW5pYf/yA7HbqM771zIAUSYEy+imoVNosGYwLXg\nD/QiIad9THYvagOHGYmgtZch7/k5HOvqlmKlkkTciyWdm+59SNY2W6PjfZxzQtRr\nt3Yfd/hNAgMBAAECggEAHB6bM/qV7swn5RbGqVqWv6wYxmHYbFT5QvhF/++2uTfx\nChuXUSbyHLqOyiviIjCIelq705cfL+OoxGC73JmrdrAswFNPYSaqoFvhyJUQO1eK\nt2q3uQdwZxXWoJuUN/o65z7k2VHvZQzv0oM1555DiUgEdUd/c5Q9E11XFTmJWXxU\nPSziBHIK/ZgBdhHxWJk4Gr9iCGIUshsEDNp3xpxAND6mpC5694S2+uCGuvshtbUC\n0ZDbBuOeBMkEDmj9qo8XJKmZH9fO3tApU5omnSp1KdwU7+lg8t/2ltjjv+zfKT5Y\nxmZBkdtm8JL1u84ifBrzJlrXTz2hwY2nK66id3NIjQKBgQDsCy6f9Xrmh1bnxxoe\n18WXHn29yBleDdNYFkE9e/F4Q5TaCjL9fS4t2vPe/zFiYQ1/suvmN1BPpR0u77mX\nK4OboqLGjM6anUW6BgtDKa4Q3h886HthoDE+2YbAAbSZbkg/44epE4WhXOKQsZ9Q\njtgZu8f9Gu+YHDY5zj+4VAe2DwKBgQC+bcQcgjwGieQbiLE4ba25yHg42MaFxCYA\nkcBtVAtURbVwzENtkswGgK+rWnx3eBK/QFbOccKklww94Cg6OFI73Wl4KbperSCm\n/i/LB1YfxdrV+ShiuRprq37giYdwhZBq1ikwnLeRWB1wkZSjmbxsaXRZiPoX+GTb\nfsOibQbn4wKBgBLBBLBS2bPtNtttd0bSD/Hky0rD1jgh0xPhmMdgzJuoivAT9V8s\njfm4tr2V+v99BIyL07BT3r6lOL9c7przKx63ekVaNKQWMM8J4eUxL5JJg6PcOMlV\n5/O9ZrZkrEuwdm8VDddCJNDgR2QFqMnGv6azw7z5YeXs/+Xx3CAyFPbDAoGBAIdI\n9f0G7Nv8VGjXOIgNK1GEQRyprIfVrOXUpi9FePL6vwcOpoyOsJGiFKsYkrpRPIhQ\njhsGKLDDenfu6sVJw+oxxz8N7hBa0IqypIOJh7700h4Xb4CLXmDFqlKcgfMHgGzW\nDtcxTxxbzDZvxnhfvMQMOxNsw7gJyKVDLnsTF8ffAoGAT1GzDqXdF6FlYNbv2sGi\nmcS8BY6F2LvEHh/1WuF8ClxZXPal0Kbn2oeoluIzQ6AMBrjj2Ab+fhgQpLrLNZJD\nhA3UoSFagGqVXlTdAGfi8feTAj0gsrqLH4gJG9lsHNbswLuZz9JMey8emhKTOsRr\nF5vo8++lEi6NqYTOR2ZHGcs=\n-----END PRIVATE KEY-----\n
  GCS_BUCKET: staging.eklesia-195019.appspot.com
  GCS_BASE_URL: https://storage.googleapis.com
  GCS_REGION: europe-west
  APP_LOG: errorlog
  APP_NAME: Eklesia
  APP_KEY: base64:eii6fGvvngtIISyt/U892fwFj4UeXaDacSIYCTa9QuQ=
  APP_DEBUG: true
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: eklesia
  DB_USERNAME: root
  DB_PASSWORD: -Tevere1996
  DB_SOCKET: "/cloudsql/eklesia-195019:europe-west1:eklesia-mysql"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "eklesia-195019:europe-west1:eklesia-mysql"
